# Generated by Django 4.2.2 on 2023-12-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Education', models.CharField(choices=[('PG', 'PG'), ('UG', 'UG')], max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Phone_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
