# Generated by Django 4.2.2 on 2023-12-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='Education',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('PG', 'PG'), ('UG', 'UG'), ('Master', 'Master')], max_length=50),
        ),
    ]
