# Generated by Django 4.2.2 on 2024-01-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sc_Name', models.CharField(max_length=100)),
                ('Sc_Principle', models.CharField(max_length=100)),
                ('Sc_Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=100)),
                ('T_Exp', models.IntegerField()),
                ('T_Sub', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('MYSQL', 'MYSQL'), ('JavaScript', 'Javascript')], max_length=50)),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100)),
                ('S_F_name', models.CharField(max_length=100)),
                ('Phone_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
                ('Teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teachers')),
            ],
        ),
    ]
